spring.application.name=LogiTrack
spring.datasource.url=jdbc:mysql://host.docker.internal:3308/LogiTrack_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=AyoubHadi120
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
notification.service.url=http://localhost:8080
management.endpoints.web.exposure.include=health,info,metrics,prometheus
info.app.name=LogiTrack
info.app.description=LogiTrack is a logistics tracking application that provides real-time tracking and management
info.app.version=1.0.0